#!/usr/bin/env python3
"""Generate the bundled AAC symbol set.

PLACEHOLDER SET — emoji rendered as SVG. Recognisable, tiny, no licensing
question. When the real pictogram library is licensed (Mulberry Symbols,
CC BY-SA, is the recommendation), drop the real SVGs into
frontend/assets/symbols/ keyed by the same ids, update LICENCE/SOURCE below,
and re-run: the DB seed and offline cache list follow automatically.

Outputs:
  frontend/assets/symbols/<id>.svg
  frontend/assets/symbols/index.json      (id -> file, for the service worker)
  supabase/seeds/symbols.sql
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYMBOL_DIR = ROOT / "frontend" / "assets" / "symbols"
SEED_DIR = ROOT / "supabase" / "seeds"

LICENCE = "placeholder"
SOURCE = "emoji (Unicode)"

# id: (emoji, label_he, [keywords_he])
SYMBOLS: dict[str, tuple[str, str, list[str]]] = {
    "yes": ("\U0001F44D", "כן", ["כן", "מסכים", "אישור"]),
    "no": ("\U0001F44E", "לא", ["לא", "מסרב", "שלילה"]),
    "more": ("➕", "עוד", ["עוד", "עוד פעם", "להוסיף"]),
    "stop": ("✋", "מספיק", ["מספיק", "עצור", "די", "להפסיק"]),
    "want": ("\U0001F64C", "רוצה", ["רוצה", "אני רוצה", "בבקשה"]),
    "dont-want": ("\U0001F645", "לא רוצה", ["לא רוצה", "לא", "מסרב"]),
    "i": ("\U0001F9D2", "אני", ["אני", "עצמי"]),
    "you": ("\U0001F9D1", "אתה", ["אתה", "את"]),
    "eat": ("\U0001F37D️", "לאכול", ["לאכול", "אוכל", "רעב", "ארוחה"]),
    "drink": ("\U0001F964", "לשתות", ["לשתות", "מים", "צמא", "שתייה"]),
    "toilet": ("\U0001F6BD", "שירותים", ["שירותים", "לשירותים", "פיפי", "קקי"]),
    "help": ("\U0001F91D", "עזרה", ["עזרה", "עזור לי", "צריך עזרה"]),
    "hurt": ("\U0001FA79", "כואב", ["כואב", "כאב", "אאוץ׳"]),
    "play": ("\U0001F9F8", "לשחק", ["לשחק", "משחק", "צעצוע"]),
    "break": ("⏸️", "הפסקה", ["הפסקה", "מנוחה", "לנוח"]),
    "home": ("\U0001F3E0", "בית", ["בית", "הביתה", "ללכת הביתה"]),
    "mom": ("\U0001F469", "אמא", ["אמא", "אימא"]),
    "dad": ("\U0001F468", "אבא", ["אבא"]),
    "music": ("\U0001F3B5", "מוזיקה", ["מוזיקה", "שיר", "לשמוע"]),
    "book": ("\U0001F4D6", "ספר", ["ספר", "לקרוא", "סיפור"]),
    "ball": ("⚽", "כדור", ["כדור", "לשחק בכדור"]),
    "sleep": ("\U0001F634", "לישון", ["לישון", "שינה", "עייף", "מיטה"]),
    "hot": ("\U0001F975", "חם", ["חם", "חום"]),
    "cold": ("\U0001F976", "קר", ["קר", "קור"]),
    "happy": ("\U0001F600", "שמח", ["שמח", "שמחה", "כיף"]),
    "sad": ("\U0001F622", "עצוב", ["עצוב", "עצב", "בוכה"]),
    "angry": ("\U0001F620", "כועס", ["כועס", "כעס", "רוגז"]),
    "scared": ("\U0001F628", "מפחד", ["מפחד", "פחד", "מפוחד"]),
    "love": ("❤️", "אוהב", ["אוהב", "אהבה", "אוהבת"]),
    "finished": ("\U0001F3C1", "לסיים", ["לסיים", "סיימתי", "גמרתי", "נגמר"]),
    "hello": ("\U0001F44B", "שלום", ["שלום", "היי", "להתראות"]),
    "thanks": ("\U0001F64F", "תודה", ["תודה", "תודה רבה"]),
    "wait": ("⌛", "לחכות", ["לחכות", "רגע", "המתנה"]),
    "go": ("\U0001F6B6", "ללכת", ["ללכת", "בוא", "נלך"]),
    "look": ("\U0001F440", "להסתכל", ["להסתכל", "תראה", "לראות"]),
    "open": ("\U0001F513", "לפתוח", ["לפתוח", "פתח"]),
}

_SVG = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" '
    'aria-label="{label}"><rect width="100" height="100" rx="14" fill="#eef2f6"/>'
    '<text x="50" y="52" font-size="58" text-anchor="middle" '
    'dominant-baseline="central">{emoji}</text></svg>'
)


def main() -> None:
    SYMBOL_DIR.mkdir(parents=True, exist_ok=True)
    SEED_DIR.mkdir(parents=True, exist_ok=True)
    index: dict[str, str] = {}
    rows: list[str] = []

    for sid, (emoji, label, keywords) in SYMBOLS.items():
        (SYMBOL_DIR / f"{sid}.svg").write_text(
            _SVG.format(label=label, emoji=emoji), encoding="utf-8"
        )
        index[sid] = f"{sid}.svg"
        kw = "{" + ",".join('"' + k.replace('"', '\\"') + '"' for k in keywords) + "}"
        rows.append(
            f"  ('{sid}', '{sid}.svg', '{label}', '{kw}', '{LICENCE}', '{SOURCE}')"
        )

    (SYMBOL_DIR / "index.json").write_text(json.dumps(index, ensure_ascii=False, indent=2))

    seed = (
        "-- Generated by scripts/build_symbols.py. Do not edit by hand.\n"
        "insert into symbols (id, file_path, label_he, keywords_he, licence, source) values\n"
        + ",\n".join(rows)
        + "\non conflict (id) do update set\n"
        "  file_path = excluded.file_path, label_he = excluded.label_he,\n"
        "  keywords_he = excluded.keywords_he, licence = excluded.licence,\n"
        "  source = excluded.source;\n"
    )
    (SEED_DIR / "symbols.sql").write_text(seed, encoding="utf-8")
    print(f"wrote {len(SYMBOLS)} symbols → {SYMBOL_DIR} and {SEED_DIR / 'symbols.sql'}")


if __name__ == "__main__":
    main()
