#!/usr/bin/env python3
"""Ingest approved Mulberry Symbols rows from the manifest into the real
symbol set.

    python scripts/build_symbols.py                    # dry run report
    python scripts/build_symbols.py --apply             # write for real
    python scripts/build_symbols.py --apply --only yes,no,love

Reads `scripts/data/mulberry_manifest.json` (see scripts/mulberry_manifest.py)
and, for every entry with status in {approved, edited}:

  - if it has a Mulberry `src`: reads that SVG from the source archive
    (--source, defaults to the Downloads zip — never extracted to disk),
    normalizes it (see normalize_svg), and writes
    frontend/assets/symbols/<id>.svg
  - if `src` is null (no adequate Mulberry equivalent — the reviewer chose
    to keep the current placeholder): the existing file is left untouched.

Also emits: a new, additive migration under supabase/migrations/ (upserting
every row's id/file_path/label_he/keywords_he/licence/source — never
touching `id` itself, which is the FK-safety invariant locked ids rely on),
and frontend/assets/symbols/LICENSE.

Interaction with build_pcs_symbols.py: that script re-skins a few core ids'
`<id>.svg` in place with (dev-only) PCS artwork and records them under
`core_overrides` in scripts/data/pcs_manifest.json. A plain run here skips
those ids so it won't clobber that file; `--only <id>` still forces the
Mulberry version back.

This SUPERSEDES the old placeholder-emoji generator. The bundled emoji set
was itself generated by an earlier version of this script from a hardcoded
dict; that dict is gone. A symbol id whose manifest entry has no Mulberry
`src` simply keeps whatever .svg is already on disk for it — nothing
regenerates the emoji artwork anymore.

After running with --apply, by hand:
  - bump SYMBOLS_VERSION in frontend/js/ui.js (defeats Railway's CDN edge
    cache — see that constant's own comment) and SHELL_CACHE in
    frontend/sw.js (ui.js changed)
  - run `supabase db push` (or let CI apply the new migration)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mulberry_manifest as mm

ROOT = Path(__file__).resolve().parent.parent
SYMBOL_DIR = ROOT / "frontend" / "assets" / "symbols"
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
PCS_MANIFEST = ROOT / "scripts" / "data" / "pcs_manifest.json"
LICENSE_TEXT = """Mulberry Symbols, version {version}
Copyright 2018-2026 Steve Lee
Licensed under Creative Commons Attribution-ShareAlike 4.0 International:
https://creativecommons.org/licenses/by-sa/4.0/

Source: https://mulberrysymbols.org/
Modified by scripts/build_symbols.py: width/height/overflow attributes and
the redundant full-canvas bounding-box path removed, role="img"/aria-label
added, files renamed to this app's symbol ids. Path data and any embedded
<style> block are unmodified. As required by ShareAlike, these modified
files remain licensed CC BY-SA 4.0.

A few core-vocabulary ids (see the manifest — entries with a null `src`)
have no adequate Mulberry equivalent and keep this project's own
placeholder artwork instead; those files are not derived from Mulberry.
"""

ET.register_namespace("", "http://www.w3.org/2000/svg")
_BBOX_PATH_RE = re.compile(r'<path[^>]*\bd="M0 0h[\d.]+v[\d.]+H0z"[^>]*/>')


def normalize_svg(raw: str, *, label_he: str) -> str:
    """Strip generator cruft, preserve everything that actually draws the
    symbol (viewBox as authored, any <style> block, all path data), add the
    project's usual role/aria-label convention. See scripts/build_symbols.py
    module docstring's design notes — do NOT run this through a generic SVG
    minifier; the source archive mixes two authoring generations (one uses
    <style class="stN"> blocks a naive optimizer would blank) and a
    hardcoded single viewBox would distort ~800 files that don't share it.
    """
    root = ET.fromstring(raw)
    for attr in ("width", "height", "overflow"):
        root.attrib.pop(attr, None)
    if root.attrib.get("id") == "Layer_1":
        del root.attrib["id"]
    root.set("role", "img")
    root.set("aria-label", label_he)
    out = ET.tostring(root, encoding="unicode")
    return _BBOX_PATH_RE.sub("", out)


@dataclass
class IngestReport:
    dry_run: bool = True
    written: list[str] = field(default_factory=list)
    unchanged_placeholder: list[str] = field(default_factory=list)
    skipped_not_approved: int = 0
    migration_path: Path | None = None


def _sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _sql_text_array(items: list[str]) -> str:
    inner = ",".join(
        '"' + i.replace("\\", "\\\\").replace('"', '\\"') + '"' for i in items
    )
    # The whole thing is also wrapped in a single-quoted SQL string literal —
    # an apostrophe inside any item (e.g. "צ'יפס") must be doubled here too,
    # or it prematurely closes that outer literal and breaks the migration.
    return "'" + ("{" + inner + "}").replace("'", "''") + "'"


def _next_migration_number() -> int:
    nums = []
    for p in MIGRATIONS_DIR.glob("[0-9][0-9][0-9][0-9]_*.sql"):
        nums.append(int(p.name[:4]))
    return (max(nums) + 1) if nums else 1


def _pcs_reskinned_ids() -> set[str]:
    """Core ids whose `<id>.svg` has been re-skinned in place with PCS art by
    scripts/build_pcs_symbols.py. Skip them here so a Mulberry re-run doesn't
    silently overwrite that file (dev-only; the PCS set may not be present)."""
    if not PCS_MANIFEST.exists():
        return set()
    return set(
        json.loads(PCS_MANIFEST.read_text(encoding="utf-8")).get("core_overrides", {})
    )


def _entries_to_ingest(manifest: dict, only: set[str] | None) -> list[tuple[str, dict]]:
    reskinned = _pcs_reskinned_ids()
    out = []
    for sid, e in manifest["entries"].items():
        if e["status"] not in ("approved", "edited"):
            continue
        if only is not None and e["id"] not in only:
            continue
        if only is None and e["id"] in reskinned:
            # PCS art currently owns <id>.svg (build_pcs_symbols.py). A plain
            # full run leaves it; `--only <id>` still forces a Mulberry revert.
            continue
        out.append((sid, e))
    out.sort(key=lambda kv: kv[1]["id"])
    return out


def run(
    *,
    dry_run: bool = True,
    only: set[str] | None = None,
    source: Path = mm.DEFAULT_SOURCE_ZIP,
    manifest_path: Path = mm.DEFAULT_MANIFEST,
    mulberry_version: str | None = None,
) -> IngestReport:
    manifest = mm.load_manifest(manifest_path)
    problems = mm.validate(manifest)
    if problems:
        raise RuntimeError(
            f"manifest has unresolved problems, fix before ingesting: {problems}"
        )

    entries = _entries_to_ingest(manifest, only)
    report = IngestReport(dry_run=dry_run)

    rows_sql = []
    with zipfile.ZipFile(source) as zf:
        for _sid, e in entries:
            app_id = e["id"]
            if e["src"]:
                raw = zf.read(f"EN-symbols/{e['src']}.svg").decode("utf-8")
                svg = normalize_svg(raw, label_he=e["label_he"])
                if not dry_run:
                    (SYMBOL_DIR / f"{app_id}.svg").write_text(svg, encoding="utf-8")
                report.written.append(app_id)
                licence, source_col = (
                    "CC BY-SA 4.0",
                    f"Mulberry Symbols {mulberry_version or manifest['mulberry_version']} (Steve Lee)",
                )
            else:
                report.unchanged_placeholder.append(app_id)
                licence, source_col = "placeholder", "emoji (Unicode)"

            rows_sql.append(
                f"  ({_sql_str(app_id)}, {_sql_str(app_id + '.svg')}, {_sql_str(e['label_he'])}, "
                f"{_sql_text_array(e['keywords_he'])}, {_sql_str(licence)}, {_sql_str(source_col)})"
            )

    if not rows_sql:
        return report

    n = _next_migration_number()
    suffix = "mulberry_symbols" if n == 11 else f"mulberry_symbols_batch{n - 10}"
    migration_path = MIGRATIONS_DIR / f"{n:04d}_{suffix}.sql"
    sql = (
        "-- Real pictogram library (Mulberry Symbols, CC BY-SA 4.0) — supersedes the\n"
        "-- placeholder rows in 0005_reference_data.sql for the ids covered here.\n"
        "-- Generated by scripts/build_symbols.py from scripts/data/mulberry_manifest.json.\n"
        "-- Do not edit by hand — re-run the script for a new batch instead.\n"
        "insert into symbols (id, file_path, label_he, keywords_he, licence, source) values\n"
        + ",\n".join(rows_sql)
        + "\non conflict (id) do update set\n"
        "  file_path = excluded.file_path, label_he = excluded.label_he,\n"
        "  keywords_he = excluded.keywords_he, licence = excluded.licence,\n"
        "  source = excluded.source;\n"
    )
    if not dry_run:
        migration_path.write_text(sql, encoding="utf-8")
        (SYMBOL_DIR / "LICENSE").write_text(
            LICENSE_TEXT.format(
                version=mulberry_version or manifest["mulberry_version"]
            ),
            encoding="utf-8",
        )
    report.migration_path = migration_path
    return report


def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--apply", action="store_true", help="write changes (default: dry run)"
    )
    p.add_argument("--only", help="comma-separated app ids to limit to")
    p.add_argument("--source", type=Path, default=mm.DEFAULT_SOURCE_ZIP)
    p.add_argument("--manifest", type=Path, default=mm.DEFAULT_MANIFEST)
    args = p.parse_args()

    only = set(args.only.split(",")) if args.only else None
    report = run(
        dry_run=not args.apply,
        only=only,
        source=args.source,
        manifest_path=args.manifest,
    )

    mode = "APPLIED" if args.apply else "DRY RUN"
    print(f"[{mode}] symbol ingestion")
    print(f"  written (real Mulberry art): {len(report.written)}  {report.written}")
    print(
        f"  unchanged (kept placeholder): {len(report.unchanged_placeholder)}  {report.unchanged_placeholder}"
    )
    if report.migration_path:
        exists = report.migration_path.exists()
        print(
            f"  migration: {report.migration_path} {'(written)' if exists else '(dry run — not written)'}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
